### ISSUE TITLE
No license for `function_name-proc-macro` crate

### ISSUE THREAD

**Issue by abr-egn** [danielhenrymantilla/rust-function_name#2]
The helper crate has no license specified in Cargo.toml, which causes problems when using a tool like `cargo deny`.

**Comment by crisidev** [comment]
I have opened a PR to solve this issue: https://github.com/danielhenrymantilla/rust-function_name/pull/3

**Comment by danielhenrymantilla** [comment]
Sorry, I somehow wasn't subscribed to my own repo and missed this, thanks @crisidev for the quick fix 🙏 

  - [Released](https://crates.io/crates/function_name/0.2.1)
